export interface Provider {
  id: string;
  name: string;
  description: string;
  icon: string;
  models: ChatModel[];
}

export interface ChatModel {
  id: string;
  name: string;
  description: string;
  providerId: string;
  capabilities: string[];
  contextWindow: number;
  pricing: 'free' | 'paid' | 'premium';
}

export const providers: Provider[] = [
  {
    id: 'xai',
    name: 'xAI',
    description: 'Grok models by xAI',
    icon: 'X',
    models: [
      {
        id: 'xai-grok-3',
        name: 'Grok-3',
        description: 'Latest flagship model with advanced reasoning',
        providerId: 'xai',
        capabilities: ['reasoning', 'code', 'tools', 'streaming', 'generation'],
        contextWindow: 200000,
        pricing: 'premium',
      },
      {
        id: 'xai-grok-3-fast',
        name: 'Grok-3 Fast',
        description: 'High-speed version of Grok-3',
        providerId: 'xai',
        capabilities: ['reasoning', 'code', 'tools', 'streaming', 'generation', 'fast'],
        contextWindow: 200000,
        pricing: 'premium',
      },
      {
        id: 'xai-grok-3-mini',
        name: 'Grok-3 Mini',
        description: 'Compact version of Grok-3',
        providerId: 'xai',
        capabilities: ['reasoning', 'code', 'tools', 'streaming', 'generation'],
        contextWindow: 128000,
        pricing: 'premium',
      },
      {
        id: 'xai-grok-3-mini-fast',
        name: 'Grok-3 Mini Fast',
        description: 'Fast compact version of Grok-3',
        providerId: 'xai',
        capabilities: ['reasoning', 'code', 'tools', 'streaming', 'generation', 'fast'],
        contextWindow: 128000,
        pricing: 'premium',
      },
      {
        id: 'xai-grok-2-1212',
        name: 'Grok-2',
        description: 'High-performance language model',
        providerId: 'xai',
        capabilities: ['reasoning', 'code', 'tools', 'streaming', 'generation'],
        contextWindow: 128000,
        pricing: 'paid',
      },
      {
        id: 'xai-grok-2-vision-1212',
        name: 'Grok-2 Vision',
        description: 'Advanced multimodal model with vision capabilities',
        providerId: 'xai',
        capabilities: ['vision', 'reasoning', 'code', 'tools', 'streaming', 'generation'],
        contextWindow: 128000,
        pricing: 'paid',
      },
      {
        id: 'xai-grok-beta',
        name: 'Grok Beta',
        description: 'Beta version with latest features',
        providerId: 'xai',
        capabilities: ['reasoning', 'code', 'tools', 'streaming', 'generation'],
        contextWindow: 128000,
        pricing: 'premium',
      },
      {
        id: 'xai-grok-vision-beta',
        name: 'Grok Vision Beta',
        description: 'Beta vision model',
        providerId: 'xai',
        capabilities: ['vision'],
        contextWindow: 128000,
        pricing: 'premium',
      },
    ],
  },
  
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'GPT models by OpenAI',
    icon: 'O',
    models: [
      {
        id:  'openai-chat-model-search',
        name: 'GPT-4.1 Search',
        description: 'Latest flagship model with search',
        providerId: 'openai',
        capabilities: ['vision', 'reasoning', 'code', 'tools', 'streaming', 'generation','search'],
        contextWindow: 200000,
        pricing: 'premium',
      },
      {
        id: 'openai-gpt-4.1',
        name: 'GPT-4.1',
        description: 'Latest flagship model with enhanced capabilities',
        providerId: 'openai',
        capabilities: ['vision', 'reasoning', 'code', 'tools', 'streaming', 'generation'],
        contextWindow: 200000,
        pricing: 'premium',
      },
      {
        id: 'openai-gpt-4.1-mini',
        name: 'GPT-4.1 Mini',
        description: 'Compact version of GPT-4.1',
        providerId: 'openai',
        capabilities: ['vision', 'reasoning', 'code', 'tools', 'streaming', 'generation'],
        contextWindow: 128000,
        pricing: 'premium',
      },
      {
        id: 'openai-gpt-4.1-nano',
        name: 'GPT-4.1 Nano',
        description: 'Ultra-compact version of GPT-4.1',
        providerId: 'openai',
        capabilities: ['vision', 'reasoning', 'code', 'tools', 'streaming', 'generation'],
        contextWindow: 64000,
        pricing: 'premium',
      },
      {
        id: 'openai-gpt-4o',
        name: 'GPT-4o',
        description: 'Most capable multimodal model',
        providerId: 'openai',
        capabilities: ['vision', 'reasoning', 'code', 'audio', 'tools', 'streaming', 'generation'],
        contextWindow: 128000,
        pricing: 'premium',
      },
      {
        id: 'openai-gpt-4o-mini',
        name: 'GPT-4o Mini',
        description: 'Fast and affordable multimodal model',
        providerId: 'openai',
        capabilities: ['vision', 'reasoning', 'code', 'fast', 'tools', 'streaming', 'generation'],
        contextWindow: 128000,
        pricing: 'paid',
      },
      {
        id: 'openai-gpt-4-turbo',
        name: 'GPT-4 Turbo',
        description: 'High-performance model with large context',
        providerId: 'openai',
        capabilities: ['reasoning', 'code', 'vision', 'tools', 'streaming', 'generation'],
        contextWindow: 128000,
        pricing: 'premium',
      },
      {
        id: 'openai-o3-mini',
        name: 'o3-mini',
        description: 'Compact reasoning model',
        providerId: 'openai',
        capabilities: ['reasoning', 'tools', 'streaming'],
        contextWindow: 128000,
        pricing: 'premium',
      },
      {
        id: 'openai-o3',
        name: 'o3',
        description: 'Advanced reasoning model',
        providerId: 'openai',
        capabilities: ['reasoning', 'tools', 'streaming'],
        contextWindow: 128000,
        pricing: 'premium',
      },
      {
        id: 'openai-o4-mini',
        name: 'o4-mini',
        description: 'Next-generation compact reasoning model',
        providerId: 'openai',
        capabilities: ['reasoning', 'tools', 'streaming'],
        contextWindow: 128000,
        pricing: 'premium',
      },
      {
        id: 'openai-o1',
        name: 'o1',
        description: 'Advanced reasoning model',
        providerId: 'openai',
        capabilities: ['vision', 'reasoning', 'tools', 'streaming'],
        contextWindow: 128000,
        pricing: 'premium',
      },
      {
        id: 'openai-o1-mini',
        name: 'o1-mini',
        description: 'Compact reasoning model',
        providerId: 'openai',
        capabilities: ['vision', 'reasoning', 'tools', 'streaming'],
        contextWindow: 128000,
        pricing: 'premium',
      },
      {
        id: 'openai-o1-preview',
        name: 'o1-preview',
        description: 'Preview reasoning model',
        providerId: 'openai',
        capabilities: ['reasoning'],
        contextWindow: 128000,
        pricing: 'premium',
      },
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    description: 'Claude models by Anthropic',
    icon: 'A',
    models: [
      {
        id: 'anthropic-claude-4-opus-20250514',
        name: 'Claude 4 Opus',
        description: 'Next-generation flagship model',
        providerId: 'anthropic',
        capabilities: ['vision', 'reasoning', 'code', 'analysis', 'tools', 'streaming', 'generation'],
        contextWindow: 300000,
        pricing: 'premium',
      },
      {
        id: 'anthropic-claude-4-sonnet-20250514',
        name: 'Claude 4 Sonnet',
        description: 'Balanced next-generation model',
        providerId: 'anthropic',
        capabilities: ['vision', 'reasoning', 'code', 'analysis', 'tools', 'streaming', 'generation'],
        contextWindow: 300000,
        pricing: 'premium',
      },
      {
        id: 'anthropic-claude-3-7-sonnet-20250219',
        name: 'Claude 3.7 Sonnet',
        description: 'Enhanced Claude 3 model',
        providerId: 'anthropic',
        capabilities: ['vision', 'reasoning', 'code', 'analysis', 'tools', 'streaming', 'generation'],
        contextWindow: 250000,
        pricing: 'premium',
      },
      {
        id: 'anthropic-claude-3-5-sonnet-20241022',
        name: 'Claude 3.5 Sonnet',
        description: 'Most intelligent model with vision capabilities',
        providerId: 'anthropic',
        capabilities: ['vision', 'reasoning', 'code', 'analysis', 'tools', 'streaming', 'generation'],
        contextWindow: 200000,
        pricing: 'premium',
      },
      {
        id: 'anthropic-claude-3-5-sonnet-20240620',
        name: 'Claude 3.5 Sonnet (June)',
        description: 'Earlier version of Claude 3.5 Sonnet',
        providerId: 'anthropic',
        capabilities: ['vision', 'reasoning', 'code', 'analysis', 'tools', 'streaming', 'generation'],
        contextWindow: 200000,
        pricing: 'premium',
      },
      {
        id: 'anthropic-claude-3-5-haiku-20241022',
        name: 'Claude 3.5 Haiku',
        description: 'Fast and affordable model',
        providerId: 'anthropic',
        capabilities: ['vision', 'reasoning', 'code', 'tools', 'streaming', 'generation'],
        contextWindow: 200000,
        pricing: 'paid',
      },
    ],
  },
  {
    id: 'google',
    name: 'Google',
    description: 'Gemini models by Google',
    icon: 'G',
    models: [
      {
        id: 'google-gemini-2.0-flash-exp',
        name: 'Gemini 2.0 Flash Exp',
        description: 'Next-generation experimental model',
        providerId: 'google',
        capabilities: ['vision', 'reasoning', 'code', 'audio', 'tools', 'streaming', 'generation'],
        contextWindow: 2000000,
        pricing: 'premium',
      },
      {
        id: 'google-gemini-1.5-pro',
        name: 'Gemini 1.5 Pro',
        description: 'Advanced multimodal model with large context',
        providerId: 'google',
        capabilities: ['vision', 'reasoning', 'code', 'audio', 'tools', 'streaming', 'generation'],
        contextWindow: 2000000,
        pricing: 'premium',
      },
      {
        id: 'google-gemini-1.5-flash',
        name: 'Gemini 1.5 Flash',
        description: 'Fast multimodal model',
        providerId: 'google',
        capabilities: ['vision', 'fast', 'code', 'tools', 'streaming', 'generation'],
        contextWindow: 1000000,
        pricing: 'paid',
      },
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral',
    description: 'Mistral AI models',
    icon: 'M',
    models: [
      {
        id: 'mistral-pixtral-large-latest',
        name: 'Pixtral Large',
        description: 'Advanced vision model with large context',
        providerId: 'mistral',
        capabilities: ['vision', 'reasoning', 'code', 'tools', 'streaming', 'generation'],
        contextWindow: 128000,
        pricing: 'premium',
      },
      {
        id: 'mistral-large-latest',
        name: 'Mistral Large',
        description: 'Most capable model for complex reasoning',
        providerId: 'mistral',
        capabilities: ['reasoning', 'code', 'multilingual', 'tools', 'streaming', 'generation'],
        contextWindow: 128000,
        pricing: 'premium',
      },
      {
        id: 'mistral-small-latest',
        name: 'Mistral Small',
        description: 'Fast and efficient model',
        providerId: 'mistral',
        capabilities: ['fast', 'code', 'tools', 'streaming', 'generation'],
        contextWindow: 32000,
        pricing: 'paid',
      },
      {
        id: 'mistral-pixtral-12b-2409',
        name: 'Pixtral 12B',
        description: 'Compact vision model',
        providerId: 'mistral',
        capabilities: ['vision', 'reasoning', 'code', 'tools', 'streaming', 'generation'],
        contextWindow: 128000,
        pricing: 'premium',
      },
    ],
  },
  {
    id: 'togetherai',
    name: 'Together.ai',
    description: 'Open-source models via Together.ai',
    icon: 'T',
    models: [
      {
        id: 'togetherai-meta-llama-3.1-70b-instruct-turbo',
        name: 'Llama 3.1 70B',
        description: 'Large open-source model by Meta',
        providerId: 'togetherai',
        capabilities: ['reasoning', 'code', 'multilingual'],
        contextWindow: 131072,
        pricing: 'paid',
      },
      {
        id: 'togetherai-meta-llama-3.1-8b-instruct-turbo',
        name: 'Llama 3.1 8B',
        description: 'Efficient open-source model',
        providerId: 'togetherai',
        capabilities: ['fast', 'code'],
        contextWindow: 131072,
        pricing: 'paid',
      },
      {
        id: 'togetherai-mistralai-mixtral-8x7b-instruct-v0.1',
        name: 'Mixtral 8x7B',
        description: 'Mixture of experts model',
        providerId: 'togetherai',
        capabilities: ['reasoning', 'code', 'multilingual'],
        contextWindow: 32768,
        pricing: 'paid',
      },
      {
        id: 'togetherai-codellama-34b-instruct',
        name: 'CodeLlama 34B',
        description: 'Specialized code generation model',
        providerId: 'togetherai',
        capabilities: ['code', 'reasoning'],
        contextWindow: 16384,
        pricing: 'paid',
      },
    ],
  },
  {
    id: 'groq',
    name: 'Groq',
    description: 'Ultra-fast inference models',
    icon: 'Q',
    models: [
      {
        id: 'groq-meta-llama-llama-4-scout-17b-16e-instruct',
        name: 'Llama 4 Scout 17B',
        description: 'Next-generation Llama model with ultra-fast inference',
        providerId: 'groq',
        capabilities: ['vision', 'reasoning', 'code', 'tools', 'streaming', 'generation'],
        contextWindow: 131072,
        pricing: 'premium',
      },
      {
        id: 'groq-llama-3.3-70b-versatile',
        name: 'Llama 3.3 70B',
        description: 'Enhanced large model with ultra-fast inference',
        providerId: 'groq',
        capabilities: ['reasoning', 'code', 'tools', 'streaming', 'generation'],
        contextWindow: 131072,
        pricing: 'paid',
      },
      {
        id: 'groq-llama-3.1-8b-instant',
        name: 'Llama 3.1 8B',
        description: 'Lightning-fast small model',
        providerId: 'groq',
        capabilities: ['fast', 'code', 'tools', 'streaming', 'generation'],
        contextWindow: 131072,
        pricing: 'paid',
      },
      {
        id: 'groq-mixtral-8x7b-32768',
        name: 'Mixtral 8x7B',
        description: 'Fast mixture of experts model',
        providerId: 'groq',
        capabilities: ['reasoning', 'code', 'fast', 'tools', 'streaming', 'generation'],
        contextWindow: 32768,
        pricing: 'paid',
      },
      {
        id: 'groq-gemma2-9b-it',
        name: 'Gemma2 9B',
        description: 'Enhanced Google model with fast inference',
        providerId: 'groq',
        capabilities: ['reasoning', 'code', 'fast', 'tools', 'streaming', 'generation'],
        contextWindow: 8192,
        pricing: 'paid',
      },
    ],
  },
  {
    id: 'vercel',
    name: 'Vercel',
    description: 'v0 models by Vercel',
    icon: 'V',
    models: [
      {
        id: 'vercel-v0-1.0-md',
        name: 'v0 1.0 MD',
        description: 'Vercel v0 model for code generation',
        providerId: 'vercel',
        capabilities: ['vision', 'generation', 'tools', 'streaming'],
        contextWindow: 128000,
        pricing: 'premium',
      },
    ],
  },
];

export const allModels: ChatModel[] = providers.flatMap(provider => provider.models);

export const getProviderById = (id: string): Provider | undefined => 
  providers.find(provider => provider.id === id);

export const getModelById = (id: string): ChatModel | undefined => 
  allModels.find(model => model.id === id);

export const getModelsByProvider = (providerId: string): ChatModel[] => 
  allModels.filter(model => model.providerId === providerId);

export const capabilityColors: Record<string, string> = {
  vision: 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200',
  reasoning: 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200',
  code: 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200',
  fast: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200',
  audio: 'bg-pink-100 text-pink-800 dark:bg-pink-900 dark:text-pink-200',
  analysis: 'bg-indigo-100 text-indigo-800 dark:bg-indigo-900 dark:text-indigo-200',
  creative: 'bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200',
  multilingual: 'bg-teal-100 text-teal-800 dark:bg-teal-900 dark:text-teal-200',
  generation: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900 dark:text-emerald-200',
  tools: 'bg-slate-100 text-slate-800 dark:bg-slate-900 dark:text-slate-200',
  streaming: 'bg-cyan-100 text-cyan-800 dark:bg-cyan-900 dark:text-cyan-200',
};

export const pricingColors: Record<string, string> = {
  free: 'bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-200',
  paid: 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200',
  premium: 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200',
};
